import { useEffect, useState, type FormEvent } from 'react';
import { BrowserRouter, Link, NavLink, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowRight, Bell, CalendarDays, Check, ChevronRight, Eye, EyeOff, HeartHandshake, LoaderCircle, LockKeyhole, UsersRound, WifiOff } from 'lucide-react';
import { post, request } from './lib/api';
import { useOnline, useToast } from './lib/hooks';
import { safeReturn, formatDate } from './lib/utils';
import { serviceWorker, syncPush } from './lib/pwa';
import { SessionContext, useSession } from './session';
import { FormError, Loading } from './components/ui';
import { Customers } from './pages/Customers';
import { Profile } from './pages/Profile';
import { Agenda } from './pages/Agenda';
import { Account } from './pages/Account';
import { AccountSettings } from './pages/AccountSettings';
import { AdvancedSettings } from './pages/AdvancedSettings';
import { AvatarMenu } from './components/AvatarMenu';
import { LogoutDialog } from './components/LogoutDialog';

export default function App() {
  const [email, setEmail] = useState<string | null>(null); const [displayName, setDisplayName] = useState(''); const [loading, setLoading] = useState(true); const [review, setReview] = useState(false); const [connectionError, setConnectionError] = useState(''); const [retry, setRetry] = useState(0); const toast = useToast();
  useEffect(() => { const controller = new AbortController(); setLoading(true); setConnectionError(''); request<{ email: string; displayName: string }>('/api/session', { signal: controller.signal }).then(s => { setEmail(s.email); setDisplayName(s.displayName); }).catch(e => { if (!controller.signal.aborted && e.status !== 401) setConnectionError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); request<{ mode: string }>('/health', { signal: controller.signal }).then(h => setReview(h.mode === 'review')).catch(() => {}); return () => controller.abort(); }, [retry]);
  useEffect(() => { const expired = () => { setEmail(null); setDisplayName(''); }; window.addEventListener('session-expired', expired); return () => window.removeEventListener('session-expired', expired); }, []);
  useEffect(() => { if (window.isSecureContext && 'serviceWorker' in navigator) serviceWorker().catch(() => {}); }, []);
  useEffect(() => { if (email) syncPush().catch(() => toast('Chưa đồng bộ được thông báo. Kiểm tra trong Tài khoản.')); }, [email, toast]);
  if (loading) return <div className="boot"><Brand/><Loading/></div>;
  if (connectionError) return <div className="boot"><Brand/><FormError message={connectionError}/><button className="button primary" onClick={() => setRetry(v => v + 1)}>Kết nối lại</button></div>;
  return <SessionContext.Provider value={{ email, setEmail, displayName, setDisplayName }}><BrowserRouter><Routes><Route path="/login" element={email ? <Navigate to="/" replace/> : <Login review={review}/>}/><Route element={email ? <Layout review={review}/> : <LoginRedirect/>}><Route index element={<Customers/>}/><Route path="customers/:id" element={<Profile/>}/><Route path="agenda" element={<Agenda/>}/><Route path="account" element={<Account/>}/><Route path="account/settings" element={<AccountSettings/>}/><Route path="account/advanced" element={<AdvancedSettings/>}/><Route path="*" element={<NotFound/>}/></Route></Routes></BrowserRouter></SessionContext.Provider>;
}
function LoginRedirect() { const location = useLocation(); return <Navigate to={`/login?return=${encodeURIComponent(location.pathname + location.search)}`} replace/>; }
function Brand() { return <div className="brand"><img src="/icon.svg" alt=""/><span>Clienté<span className="brand-period">.</span></span></div>; }
function Layout({ review }: { review: boolean }) {
  const [logoutOpen, setLogoutOpen] = useState(false); const location = useLocation(); const online = useOnline();
  const section = location.pathname.startsWith('/agenda') ? 'Lịch chăm sóc' : location.pathname === '/account/advanced' ? 'Cài đặt nâng cao' : location.pathname === '/account/settings' ? 'Cài đặt' : location.pathname.startsWith('/account') ? 'Thông tin cá nhân' : 'Khách hàng';
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'instant' }); document.title = `Clienté · ${section}`; }, [location.pathname, section]);
  return <div className="app-shell"><a className="skip-link" href="#main">Đến nội dung chính</a><aside className="sidebar"><Link className="brand-link" to="/" aria-label="Clienté — Danh sách khách"><Brand/></Link><span className="sidebar-caption">THE ART OF CLIENT CARE</span><div className="sidebar-rule"/><span className="nav-label">KHÔNG GIAN LÀM VIỆC</span><nav aria-label="Điều hướng chính"><NavLink to="/" end className={({ isActive }) => isActive || location.pathname.startsWith('/customers/') ? 'active' : ''}><UsersRound size={19}/><span>Khách hàng</span><ChevronRight size={14}/></NavLink><NavLink to="/agenda"><CalendarDays size={19}/><span>Lịch chăm sóc</span><ChevronRight size={14}/></NavLink></nav><div className="sidebar-message"><HeartHandshake size={25} strokeWidth={1.2}/><p>Sự quan tâm tốt đẹp<br/>luôn được ghi nhớ.</p><span>YOUR RELATIONSHIPS MATTER</span></div><AvatarMenu variant="sidebar" onLogout={() => setLogoutOpen(true)}/></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>Không gian của bạn</span><ChevronRight size={12}/><strong>{section}</strong></div><Link className="mobile-brand" to="/"><Brand/></Link><div className="topbar-actions"><span className="today-label">{formatDate(new Date().toISOString())}</span><Link to="/agenda" className="icon-button" aria-label="Mở lịch nhắc"><Bell size={19}/></Link><AvatarMenu variant="top" onLogout={() => setLogoutOpen(true)}/></div></header>{review && <div className="review-banner"><span>REVIEW</span> Dữ liệu thử riêng · Thông báo thật đang tắt</div>}{!online && <div className="offline-banner" role="status"><WifiOff size={16}/> Đang ngoại tuyến. Kết nối lại để lưu các thay đổi.</div>}<main id="main" tabIndex={-1}><Outlet/></main><footer className="app-footer"><span>Clienté <span>·</span> Những mối quan hệ bền lâu.</span><span>CHĂM SÓC BẰNG SỰ THẤU HIỂU</span></footer></div><nav className="mobile-nav" aria-label="Điều hướng điện thoại"><NavLink to="/" end className={({ isActive }) => isActive || location.pathname.startsWith('/customers/') ? 'active' : ''}><UsersRound size={20}/><span>Khách hàng</span></NavLink><NavLink to="/agenda"><CalendarDays size={20}/><span>Lịch chăm sóc</span></NavLink><AvatarMenu variant="mobile" onLogout={() => setLogoutOpen(true)}/></nav>{logoutOpen && <LogoutDialog onClose={() => setLogoutOpen(false)}/>}</div>;
}
function Login({ review }: { review: boolean }) {
  const [email, setEmailInput] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const { setEmail, setDisplayName } = useSession(); const [params] = useSearchParams(); const navigate = useNavigate();
  async function login(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result = await post<{ email: string; displayName: string }>('/auth/login', { email, password }); setEmail(result.email); setDisplayName(result.displayName); navigate(safeReturn(params.get('return')), { replace: true }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="login-page"><section className="login-story"><Brand/><span className="login-story-label">THE ART OF CLIENT CARE</span><div className="login-story-content"><span className="eyebrow">MỖI MỐI QUAN HỆ, MỘT HÀNH TRÌNH</span><h1>Sự quan tâm.<br/>Dấu ấn dài lâu.</h1><p>Một không gian tinh gọn để ghi nhớ khách hàng,<br className="desktop-only"/> chăm sóc đúng lúc và đồng hành sau mỗi chuyến xe.</p><div className="login-illustration" aria-hidden="true"><svg viewBox="0 0 600 200"><path d="M-40 198C120 198 60 50 285 50S530 175 670 20"/><path d="M-40 214C130 214 80 65 285 65S510 190 670 36"/><path d="M-40 182C100 182 40 35 285 35S550 160 670 4"/><circle cx="285" cy="49" r="16"/><circle cx="285" cy="49" r="6"/><path d="M-20 150h650" className="illustration-baseline"/></svg><span>MỌI HÀNH TRÌNH ĐỀU BẮT ĐẦU TỪ MỘT KẾT NỐI.</span></div></div><div className="login-story-footer"><span>CLIENTÉ / PERSONAL CLIENT CARE</span><HeartHandshake size={21} strokeWidth={1.1}/></div></section><section className="login-form-side"><div className="login-form-wrap"><div className="mobile-login-brand"><Brand/></div><span className="eyebrow">CHÀO MỪNG TRỞ LẠI</span><h2>Tiếp nối những<br/>mối quan hệ tốt đẹp.</h2><p>Đăng nhập để mở danh sách khách hàng của bạn.</p>{review && <div className="login-review"><span className="review-label">REVIEW</span> Môi trường thử với dữ liệu hư cấu.<button className="text-button" onClick={() => { setEmailInput('review@clientstudio.local'); setPassword('Review123!'); }}>Điền tài khoản thử <ArrowRight size={14}/></button></div>}<form onSubmit={login}><fieldset disabled={busy}><label>Email nhân viên<input autoFocus required type="email" autoComplete="username" maxLength={254} placeholder="ban@congty.vn" value={email} onChange={e => setEmailInput(e.target.value)}/></label><label>Mật khẩu<div className="password-field"><input required type={visible ? 'text' : 'password'} autoComplete="current-password" maxLength={256} placeholder="Nhập mật khẩu của bạn" value={password} onChange={e => setPassword(e.target.value)}/><button type="button" className="icon-button" aria-label={visible ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'} onClick={() => setVisible(v => !v)}>{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label></fieldset><FormError message={error}/><button type="submit" className="button primary login-submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18}/> : null}{busy ? 'Đang đăng nhập…' : 'Vào không gian của bạn'}<ArrowRight size={18}/></button></form><div className="login-secure"><LockKeyhole size={16}/><span>Hồ sơ riêng. Kết nối an toàn.</span></div><div className="login-help"><Check size={15}/><p>Cần tài khoản hoặc quên mật khẩu?<br/>Liên hệ người quản lý để được hỗ trợ.</p></div></div><footer>Chăm sóc khách hàng, bằng sự thấu hiểu.</footer></section></div>;
}
function NotFound() { return <div className="empty"><h1>Trang này chưa có.</h1><p>Trở về danh sách để tiếp tục chăm sóc khách hàng.</p><Link to="/" className="button primary">Danh sách khách hàng</Link></div>; }
