import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/be-vietnam-pro/latin-400.css';
import '@fontsource/be-vietnam-pro/vietnamese-400.css';
import '@fontsource/be-vietnam-pro/latin-500.css';
import '@fontsource/be-vietnam-pro/vietnamese-500.css';
import '@fontsource/be-vietnam-pro/latin-600.css';
import '@fontsource/be-vietnam-pro/vietnamese-600.css';
import '@fontsource/cormorant-garamond/latin-500.css';
import '@fontsource/cormorant-garamond/vietnamese-500.css';
import './styles.css';
import App from './App';
import { ToastProvider } from './lib/hooks';
import { ConfirmationProvider } from './components/confirmation';
import { captureInstallPrompt } from './lib/pwa';
window.addEventListener('beforeinstallprompt', captureInstallPrompt);
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ToastProvider><ConfirmationProvider><App/></ConfirmationProvider></ToastProvider></React.StrictMode>);
