import { useState, type FormEvent } from 'react';
import { Plus, Trash2, CarFront, CalendarDays, Clock3 } from 'lucide-react';
import { ApiError, post, put } from '../lib/api';
import { channels, kinds, statuses, type Customer, type CustomerInput, type Occurrence, type Reminder, type ReminderInput } from '../lib/types';
import { localDateTime, today, zone } from '../lib/utils';
import { useToast } from '../lib/hooks';
import { FormActions, FormError, FormFields, Modal } from './ui';
import { useDiscardChanges } from './confirmation';

const blank: CustomerInput = { name: '', phone: '', birthDate: null, interests: '', notes: '', preferredContact: '', status: 'new', vehicles: [] };
const future = (days = 1) => localDateTime(new Date(Date.now() + days * 86400000));
const newReminder = (): ReminderInput => ({ kind: 'afterPurchase', content: '', localDateTime: future(), timeZone: zone, repeat: 'once', leadDays: 0, leapDayPolicy: null });
const templates: Record<string, string> = { birthday: 'Gọi điện chúc mừng sinh nhật', afterPurchase: 'Hỏi thăm trải nghiệm sử dụng xe', maintenance: 'Liên hệ nhắc lịch bảo dưỡng xe', delivery: 'Chúc mừng kỷ niệm ngày nhận xe', consulting: 'Trao đổi nhu cầu và tư vấn xe', other: '' };

export function CustomerForm({ customer, onClose, onSaved }: { customer?: Customer; onClose: () => void; onSaved: (customer: Customer) => void }) {
  const initial: CustomerInput = customer ? { name: customer.name, phone: customer.phone, birthDate: customer.birthDate || null, interests: customer.interests || '', notes: customer.notes || '', preferredContact: customer.preferredContact || '', status: customer.status, vehicles: customer.vehicles.map(v => ({ ...v })) } : blank;
  const [draft, setDraft] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [duplicate, setDuplicate] = useState(''); const toast = useToast();
  const change = <K extends keyof CustomerInput>(key: K, value: CustomerInput[K]) => setDraft(v => ({ ...v, [key]: value }));
  const close = useDiscardChanges({ dirty: JSON.stringify(initial) !== JSON.stringify(draft), busy, onClose, description: 'Các thay đổi trong hồ sơ khách hàng chưa được lưu. Bạn muốn tiếp tục chỉnh sửa hay bỏ những thay đổi này?' });
  async function save(e: FormEvent) {
    e.preventDefault(); setBusy(true); setError('');
    try {
      const input = { ...draft, vehicles: draft.vehicles.filter(v => v.model.trim() || v.plate.trim() || v.deliveryDate).map(v => ({ ...v, id: v.id || null })) };
      const result = customer ? await put<Customer>(`/api/customers/${customer.id}`, input) : await post<Customer>('/api/customers', input);
      toast(customer ? 'Đã cập nhật hồ sơ khách hàng.' : 'Đã thêm khách hàng mới.'); onSaved(result);
    } catch (e) {
      if (e instanceof ApiError && e.status === 409 && e.data.duplicate) { setDuplicate((e.data.duplicate as { name: string }).name); }
      setError((e as Error).message);
    } finally { setBusy(false); }
  }
  return <Modal title={customer ? 'Chỉnh sửa hồ sơ' : 'Một mối quan hệ mới'} subtitle="Lưu những điều quan trọng, để mỗi lần chăm sóc đều đúng lúc." onClose={close} busy={busy} wide><form onSubmit={save}><FormFields busy={busy}>
    <div className="section-label"><span>01</span> Thông tin khách hàng</div>
    <div className="form-grid"><label>Họ và tên <b>*</b><input autoFocus required maxLength={200} autoComplete="name" placeholder="Ví dụ: Nguyễn Minh Anh" value={draft.name} onChange={e => change('name', e.target.value)}/></label><label>Số điện thoại <b>*</b><input required type="tel" inputMode="tel" autoComplete="tel" maxLength={32} placeholder="090…" value={draft.phone} onChange={e => { change('phone', e.target.value); setDuplicate(''); change('confirmDuplicate', false); }}/></label><label>Ngày sinh<input type="date" max={today()} value={draft.birthDate || ''} onChange={e => change('birthDate', e.target.value || null)}/></label><label>Trạng thái<select value={draft.status} onChange={e => change('status', e.target.value)}>{Object.entries(statuses).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label></div>
    {duplicate && <div className="duplicate-note"><strong>Số điện thoại đã thuộc hồ sơ {duplicate}.</strong><label className="check"><input type="checkbox" checked={draft.confirmDuplicate || false} onChange={e => change('confirmDuplicate', e.target.checked)}/> Tôi xác nhận đây là một khách hàng khác.</label></div>}
    <label>Kênh và thời gian liên hệ phù hợp<input maxLength={500} placeholder="Ví dụ: gọi điện sau 15:00, ưu tiên tin nhắn" value={draft.preferredContact} onChange={e => change('preferredContact', e.target.value)}/></label>
    <div className="section-label"><span>02</span> Xe của khách hàng <button className="text-button" type="button" disabled={draft.vehicles.length >= 20} onClick={() => change('vehicles', [...draft.vehicles, { model: '', plate: '', deliveryDate: null }])}><Plus size={16}/> Thêm xe</button></div>
    {!draft.vehicles.length && <div className="inline-empty"><CarFront size={22}/><span>Chưa có thông tin xe. Bạn có thể bổ sung sau.</span></div>}
    {draft.vehicles.map((v, i) => <div className="vehicle-form" key={v.id || i}><div className="vehicle-form-head"><strong>Xe {i + 1}</strong><button className="icon-button danger" aria-label={`Xóa xe ${i + 1}`} type="button" onClick={() => change('vehicles', draft.vehicles.filter((_, j) => j !== i))}><Trash2 size={16}/></button></div><div className="form-grid"><label className="span-2">Dòng xe<input maxLength={200} placeholder="Mercedes-Benz C 200 Avantgarde" value={v.model} onChange={e => change('vehicles', draft.vehicles.map((car, j) => j === i ? { ...car, model: e.target.value } : car))}/></label><label>Biển số<input maxLength={32} placeholder="51K-…" value={v.plate} onChange={e => change('vehicles', draft.vehicles.map((car, j) => j === i ? { ...car, plate: e.target.value } : car))}/></label><label>Ngày giao xe<input type="date" value={v.deliveryDate || ''} onChange={e => change('vehicles', draft.vehicles.map((car, j) => j === i ? { ...car, deliveryDate: e.target.value || null } : car))}/></label></div></div>)}
    <div className="section-label"><span>03</span> Những điều cần nhớ</div><label>Sở thích<input maxLength={10000} placeholder="Golf, du lịch, yêu thích công nghệ…" value={draft.interests} onChange={e => change('interests', e.target.value)}/></label><label>Ghi chú riêng<textarea maxLength={10000} rows={3} placeholder="Nhu cầu, thói quen và những điều giúp bạn chăm sóc tốt hơn…" value={draft.notes} onChange={e => change('notes', e.target.value)}/></label>
  </FormFields><FormError message={error}/><FormActions busy={busy} onCancel={close} label={customer ? 'Lưu hồ sơ' : 'Thêm khách hàng'}/></form></Modal>;
}

function ReminderFields({ value, onChange }: { value: ReminderInput; onChange: (value: ReminderInput) => void }) {
  const change = <K extends keyof ReminderInput>(key: K, v: ReminderInput[K]) => onChange({ ...value, [key]: v });
  return <><div className="form-grid"><label>Loại chăm sóc<select value={value.kind} onChange={e => onChange({ ...value, kind: e.target.value, content: templates[e.target.value], repeat: ['birthday', 'delivery'].includes(e.target.value) ? 'annual' : 'once' })}>{Object.entries(kinds).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Lặp lại<select value={value.repeat} onChange={e => change('repeat', e.target.value)}><option value="once">Một lần</option><option value="annual">Hằng năm</option></select></label></div>
    <label>Nội dung lời nhắc <b>*</b><textarea autoFocus required maxLength={2000} rows={3} placeholder="Bạn muốn nhắc mình điều gì?" value={value.content} onChange={e => change('content', e.target.value)}/></label>
    <div className="form-grid"><label>Ngày và giờ <b>*</b><input type="datetime-local" required min={localDateTime(new Date(Date.now() + 60000))} value={value.localDateTime.slice(0, 16)} onChange={e => change('localDateTime', e.target.value)}/></label><label>Nhắc trước<select value={value.leadDays} onChange={e => change('leadDays', Number(e.target.value))}><option value={0}>Đúng giờ đã đặt</option><option value={1}>Trước 1 ngày</option><option value={3}>Trước 3 ngày</option></select></label></div>
    {value.repeat === 'annual' && value.localDateTime.slice(5, 10) === '02-29' && <label>Trong năm không có ngày 29/02 <b>*</b><select required value={value.leapDayPolicy || ''} onChange={e => change('leapDayPolicy', e.target.value)}><option value="">Chọn ngày thay thế</option><option value="feb28">Nhắc vào 28/02</option><option value="mar1">Nhắc vào 01/03</option></select></label>}
    <div className="field-note"><Clock3 size={15}/> Giờ Việt Nam (UTC+7). Lịch được lưu cả khi bạn chưa bật thông báo.</div>
  </>;
}
export function ReminderForm({ customerId, customerName, reminder, onClose, onSaved }: { customerId: string; customerName: string; reminder?: Reminder; onClose: () => void; onSaved: () => void }) {
  const [initial] = useState(() => reminder ? { ...reminder } : newReminder()); const [value, setValue] = useState<ReminderInput>(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toast = useToast();
  const close = useDiscardChanges({ dirty: JSON.stringify(value) !== JSON.stringify(initial), busy, onClose, description: 'Lịch nhắc đang chỉnh sửa chưa được lưu. Bạn có thể quay lại để hoàn thiện lịch chăm sóc.' });
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { if (reminder) await put(`/api/reminders/${reminder.id}`, value); else await post(`/api/customers/${customerId}/reminders`, value); toast('Đã lưu lịch chăm sóc.'); onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title={reminder ? 'Chỉnh sửa lịch nhắc' : 'Hẹn một lần chăm sóc'} subtitle={customerName} onClose={close} busy={busy}><form onSubmit={save}><FormFields busy={busy}><ReminderFields value={value} onChange={setValue}/></FormFields><FormError message={error}/><FormActions busy={busy} onCancel={close} label="Lưu lịch nhắc"/></form></Modal>;
}
export function ContactForm({ customerId, customerName, occurrence, onClose, onSaved }: { customerId: string; customerName: string; occurrence?: Occurrence; onClose: () => void; onSaved: () => void }) {
  const [initial] = useState(() => ({ at: localDateTime(), channel: 'call', content: '' })); const [value, setValue] = useState(initial); const [followup, setFollowup] = useState(false); const [next, setNext] = useState<ReminderInput>({ ...newReminder(), localDateTime: future(7) }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toast = useToast();
  const close = useDiscardChanges({ dirty: JSON.stringify(value) !== JSON.stringify(initial) || followup, busy, onClose, description: 'Nội dung chăm sóc và lịch hẹn tiếp theo chưa được lưu. Chọn tiếp tục chỉnh sửa để giữ lại những gì bạn đang nhập.' });
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await post(`/api/customers/${customerId}/contacts`, { ...value, at: new Date(`${value.at}+07:00`).toISOString(), occurrenceId: occurrence?.id || null, nextReminder: followup ? next : null }); toast('Đã ghi nhận chăm sóc' + (followup ? ' và đặt lịch tiếp theo.' : '.')); onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Ghi nhận chăm sóc" subtitle={customerName + (occurrence ? ' · Đồng thời hoàn thành lần nhắc này' : '')} onClose={close} busy={busy}><form onSubmit={save}><FormFields busy={busy}><div className="form-grid"><label>Kênh liên hệ<select value={value.channel} onChange={e => setValue(v => ({ ...v, channel: e.target.value }))}>{Object.entries(channels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Thời điểm thực hiện<input type="datetime-local" required max={localDateTime()} value={value.at} onChange={e => setValue(v => ({ ...v, at: e.target.value }))}/></label></div><label>Nội dung và kết quả <b>*</b><textarea autoFocus required maxLength={10000} rows={5} placeholder="Đã trao đổi điều gì? Khách cần hỗ trợ thêm gì?" value={value.content} onChange={e => setValue(v => ({ ...v, content: e.target.value }))}/></label><label className="check followup"><input type="checkbox" checked={followup} onChange={e => setFollowup(e.target.checked)}/><CalendarDays size={18}/> Hẹn lần chăm sóc tiếp theo</label>{followup && <div className="followup-fields"><ReminderFields value={next} onChange={setNext}/></div>}</FormFields><FormError message={error}/><FormActions busy={busy} onCancel={close} label="Lưu chăm sóc"/></form></Modal>;
}
export function SnoozeForm({ occurrence, onClose, onSaved }: { occurrence: Occurrence; onClose: () => void; onSaved: () => void }) {
  const [initial] = useState(() => future()); const [at, setAt] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toast = useToast();
  const close = useDiscardChanges({ dirty: at !== initial, busy, onClose, description: 'Thời điểm dời lịch chưa được lưu. Bạn muốn tiếp tục chọn giờ hay bỏ thay đổi này?' });
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); try { await post(`/api/occurrences/${occurrence.id}/snooze`, { localDateTime: at, timeZone: zone }); toast('Đã dời lần nhắc. Các lần lặp khác được giữ nguyên.'); onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Dời lần nhắc này" subtitle="Chọn một thời điểm phù hợp hơn." onClose={close} busy={busy}><form onSubmit={save}><FormFields busy={busy}><label>Ngày và giờ mới<input autoFocus type="datetime-local" required min={localDateTime(new Date(Date.now() + 60000))} value={at} onChange={e => setAt(e.target.value)}/></label><div className="field-note">Giờ Việt Nam (UTC+7). Chỉ thay đổi lần nhắc đang chọn.</div></FormFields><FormError message={error}/><FormActions busy={busy} onCancel={close} label="Dời lịch"/></form></Modal>;
}
