import { useEffect, useState } from 'react';
import { Apple, Bell, BookOpen, Check, Download, Smartphone, ArrowRight, LoaderCircle } from 'lucide-react';
import { AccountNavigation } from '../components/AccountNavigation';
import { useResource, useToast } from '../lib/hooks';
import { disablePush, enablePush, isInstalled, isIOS, pushSupported, serviceWorker, getInstallPrompt, clearInstallPrompt, type PushConfig, type InstallPrompt } from '../lib/pwa';
import { FormError } from '../components/ui';
import { InstallGuide } from '../components/InstallGuide';

export function AccountSettings() {
  const [guideOpen, setGuideOpen] = useState(false);
  const config = useResource<PushConfig>('/api/push/config'); const [subscribed, setSubscribed] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [installed, setInstalled] = useState(isInstalled()); const [prompt, setPrompt] = useState<InstallPrompt | undefined>(getInstallPrompt); const toast = useToast();
  useEffect(() => { if (pushSupported()) serviceWorker().then(r => r.pushManager.getSubscription()).then(s => setSubscribed(!!s)).catch(() => {}); const install = () => setPrompt(getInstallPrompt()); const installed = () => { setInstalled(true); setPrompt(undefined); clearInstallPrompt(); }; window.addEventListener('install-prompt-ready', install); window.addEventListener('appinstalled', installed); return () => { window.removeEventListener('install-prompt-ready', install); window.removeEventListener('appinstalled', installed); }; }, []);
  async function push() { setBusy('push'); setError(''); try { if (subscribed) { await disablePush(); setSubscribed(false); toast('Đã tắt thông báo trên thiết bị này.'); } else { await enablePush(config.data!); setSubscribed(true); toast('Đã bật lời nhắc trên thiết bị này.'); } } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function install() {
    const current = getInstallPrompt(); if (!current) { setGuideOpen(true); return; }
    setBusy('install'); setError('');
    try { await current.prompt(); const choice = await current.userChoice; if (choice.outcome === 'dismissed') setGuideOpen(true); }
    catch (e) { setError((e as Error).message); setGuideOpen(true); }
    finally { setPrompt(undefined); clearInstallPrompt(); setBusy(''); }
  }
  const needsHomeScreen = isIOS() && !installed;
  return <><section className="page-heading"><div><span className="eyebrow">KHÔNG GIAN CỦA BẠN</span><h1>Cài đặt<span className="title-dot">.</span></h1><p>Thiết lập để mỗi lời nhắc luôn đến đúng nơi.</p></div></section><AccountNavigation/><div className="account-settings device-settings"><section className="panel setting-card"><div className="setting-icon"><Bell size={24} strokeWidth={1.4}/></div><div className="setting-body"><div className="setting-heading"><h2>Lời nhắc trên thiết bị</h2><span className={`status ${subscribed && config.data?.enabled ? 'purchased' : ''}`}><i/>{subscribed && config.data?.enabled ? 'Đã bật' : 'Chưa bật'}</span></div><p>Nhận thông báo khi lịch chăm sóc đến hạn, kể cả khi bạn không mở Clienté.</p>{config.error ? <FormError message={config.error}/> : !config.loading && !config.data?.enabled ? <div className="setting-hint">Môi trường hiện tại chưa bật thông báo thật. Bạn vẫn có thể tạo và quản lý lịch chăm sóc.</div> : needsHomeScreen ? <div className="setting-hint">Trên iPhone: mở bằng Safari → Chia sẻ → Thêm vào Màn hình chính. Sau đó mở Clienté từ biểu tượng và bật thông báo.</div> : !pushSupported() ? <div className="setting-hint">Mở bằng trình duyệt hỗ trợ qua HTTPS để bật thông báo.</div> : null}<button className="button primary" disabled={!!busy || config.loading || !!config.error || !config.data?.enabled || needsHomeScreen || !pushSupported()} onClick={push}>{busy === 'push' ? <LoaderCircle className="spin" size={16}/> : subscribed ? <Check size={16}/> : <Bell size={16}/>} {subscribed ? 'Tắt trên thiết bị này' : 'Bật thông báo'}</button><small>Lời nhắc cần mạng và quyền thông báo. Cài đặt Không làm phiền có thể ảnh hưởng việc hiển thị.</small></div></section><section className="panel setting-card"><div className="setting-icon"><Smartphone size={25} strokeWidth={1.4}/></div><div className="setting-body"><div className="setting-heading"><h2>Clienté trên màn hình chính</h2>{installed && <span className="status purchased"><i/>Đã cài</span>}</div><p>Mở nhanh bằng biểu tượng riêng, với không gian rộng hơn cho việc chăm sóc khách hàng.</p><div className="install-platform-preview"><span><Apple size={18}/> iPhone / iOS <small>Safari</small></span><span><Smartphone size={18}/> Android / Samsung <small>Chrome</small></span></div><p className="install-guide-caption">Hướng dẫn từng bước, có hình minh họa vị trí cần bấm.</p><div className="install-card-actions">{!installed && prompt && <button type="button" className="button primary" disabled={!!busy} onClick={install}>{busy === "install" ? <LoaderCircle size={16} className="spin"/> : <Download size={16}/>} Cài Clienté</button>}<button type="button" className="button secondary" onClick={() => setGuideOpen(true)}><BookOpen size={16}/> Hướng dẫn cài đặt<ArrowRight size={15}/></button></div></div></section><FormError message={error}/></div>{guideOpen && <InstallGuide onClose={() => setGuideOpen(false)} installed={installed} pushEnabled={config.data?.enabled}/>}</>;
}
