import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { CalendarDays, Check, Clock3, Plus, Search, ArrowUpRight } from 'lucide-react';
import { useResource, useToast } from '../lib/hooks';
import { post } from '../lib/api';
import { normalize, today, localDateTime, formatDate, clockTime } from '../lib/utils';
import { kinds, type AgendaItem, type Customer } from '../lib/types';
import { Avatar, Empty, ErrorState, Loading, Modal } from '../components/ui';
import { ContactForm, ReminderForm, SnoozeForm } from '../components/forms';
import { useConfirm } from '../components/confirmation';
export function Agenda() {
  const confirm = useConfirm();
  const resource = useResource<AgendaItem[]>('/api/agenda'); const customers = useResource<Customer[]>('/api/customers'); const [params, setParams] = useSearchParams(); const filter = params.get('filter') || 'all';
  const [search, setSearch] = useState(''); const [action, setAction] = useState<{ type: 'snooze' | 'contact'; item: AgendaItem }>(); const [choosing, setChoosing] = useState(false); const [newCustomer, setNewCustomer] = useState<Customer>(); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const toast = useToast();
  const list = (resource.data || []).filter(item => { const day = localDateTime(new Date(item.occurrence.scheduledAt)).slice(0, 10); return normalize(`${item.customerName} ${item.reminder.content} ${kinds[item.reminder.kind]}`).includes(normalize(search)) && (filter === 'all' || filter === 'today' && day === today() || filter === 'overdue' && new Date(item.occurrence.scheduledAt).getTime() < Date.now() || filter === 'week' && day >= today() && new Date(item.occurrence.scheduledAt).getTime() < Date.now() + 7 * 86400000); });
  const grouped = new Map<string, AgendaItem[]>(); for (const item of list) { const date = localDateTime(new Date(item.occurrence.scheduledAt)).slice(0, 10); grouped.set(date, [...(grouped.get(date) || []), item]); }
  async function complete(item: AgendaItem) { if (busy || !await confirm({ title: 'Hoàn thành lần nhắc?', description: `Đánh dấu “${item.reminder.content}” của ${item.customerName} là đã hoàn thành. Các lần lặp tiếp theo vẫn được giữ.`, confirmLabel: 'Hoàn thành', cancelLabel: 'Quay lại', tone: 'success' })) return; setBusy(item.occurrence.id); setError(''); try { await post(`/api/occurrences/${item.occurrence.id}/complete`); toast('Đã hoàn thành lần nhắc.'); resource.reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const saved = () => { setAction(undefined); setNewCustomer(undefined); resource.reload(); };
  return <><section className="page-heading"><div><span className="eyebrow">NHỮNG CUỘC HẸN ĐÁNG NHỚ</span><h1>Lịch chăm sóc<span className="title-dot">.</span></h1><p>Đúng người, đúng thời điểm. Không bỏ lỡ một lời hỏi thăm.</p></div><button className="button primary" onClick={() => setChoosing(true)}><Plus size={18}/> Đặt lịch nhắc</button></section><section className="panel agenda-panel"><div className="agenda-toolbar"><div className="filter-tabs">{[['all', 'Tất cả'], ['today', 'Hôm nay'], ['week', '7 ngày tới'], ['overdue', 'Quá hạn']].map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} aria-pressed={filter === key} onClick={() => setParams(key === 'all' ? {} : { filter: key })}>{label}</button>)}</div><div className="search-field"><Search size={17}/><input aria-label="Tìm lịch chăm sóc" placeholder="Tìm khách hoặc nội dung nhắc…" value={search} onChange={e => setSearch(e.target.value)}/></div></div>{error && <div className="form-error" role="alert">{error}</div>}{resource.loading ? <Loading/> : resource.error ? <ErrorState message={resource.error} retry={resource.reload}/> : !list.length ? <Empty title="Chưa có lịch trong mục này" text="Đặt một lịch mới hoặc đổi bộ lọc để xem các cuộc hẹn khác." action={<button className="button secondary" onClick={() => setChoosing(true)}><Plus size={16}/> Đặt lịch nhắc</button>}/> : <div className="agenda-groups">{[...grouped].map(([date, items]) => <div className="agenda-group" key={date}><h2><CalendarDays size={18}/>{date === today() ? 'Hôm nay' : formatDate(date)}<span>{items.length} lịch hẹn</span></h2>{items.map(item => <article className={`agenda-entry ${new Date(item.occurrence.scheduledAt).getTime() < Date.now() ? 'overdue' : ''}`} key={item.occurrence.id}><div className="entry-time"><strong>{clockTime(item.occurrence.scheduledAt)}</strong><span>{new Date(item.occurrence.scheduledAt).getTime() < Date.now() ? 'Quá hạn' : kinds[item.reminder.kind]}</span></div><Link className="entry-customer" to={`/customers/${item.customerId}?tab=reminders&occurrence=${item.occurrence.id}`}><Avatar name={item.customerName} id={item.avatarId}/><div><h3>{item.customerName} <ArrowUpRight size={14}/></h3><p>{item.reminder.content}</p><small>{kinds[item.reminder.kind]}{item.reminder.repeat === 'annual' ? ' · Hằng năm' : ''}</small></div></Link><div className="entry-actions"><button className="button small secondary" disabled={busy === item.occurrence.id} onClick={() => setAction({ type: 'contact', item })}>Ghi nhận</button><button className="icon-button" aria-label={`Dời lịch của ${item.customerName}`} disabled={busy === item.occurrence.id} onClick={() => setAction({ type: 'snooze', item })}><Clock3 size={18}/></button><button className="icon-button success" aria-label={`Hoàn thành lịch của ${item.customerName}`} disabled={busy === item.occurrence.id} onClick={() => complete(item)}><Check size={18}/></button></div></article>)}</div>)}</div>}</section>
    {choosing && <Modal title="Bạn muốn chăm sóc ai?" subtitle="Chọn khách hàng để đặt một lịch nhắc mới." onClose={() => setChoosing(false)}>{customers.loading ? <Loading/> : customers.error ? <ErrorState message={customers.error} retry={customers.reload}/> : customers.data?.length ? <CustomerPicker list={customers.data} onSelect={c => { setChoosing(false); setNewCustomer(c); }}/> : <Empty title="Thêm khách hàng trước" text="Lịch chăm sóc luôn thuộc về một hồ sơ khách hàng." action={<Link className="button primary" to="/">Đến danh sách khách</Link>}/>}</Modal>}
    {newCustomer && <ReminderForm customerId={newCustomer.id} customerName={newCustomer.name} onClose={() => setNewCustomer(undefined)} onSaved={saved}/>}
    {action?.type === 'contact' && <ContactForm customerId={action.item.customerId} customerName={action.item.customerName} occurrence={action.item.occurrence} onClose={() => setAction(undefined)} onSaved={saved}/>}
    {action?.type === 'snooze' && <SnoozeForm occurrence={action.item.occurrence} onClose={() => setAction(undefined)} onSaved={saved}/>}</>;
}
function CustomerPicker({ list, onSelect }: { list: Customer[]; onSelect: (c: Customer) => void }) { const [search, setSearch] = useState(''); const filtered = list.filter(c => normalize(c.name + ' ' + c.phone).includes(normalize(search))); return <><div className="search-field"><Search size={18}/><input autoFocus aria-label="Tìm khách để đặt lịch" placeholder="Tìm tên hoặc số điện thoại…" value={search} onChange={e => setSearch(e.target.value)}/></div><div className="customer-picker">{filtered.map(c => <button key={c.id} onClick={() => onSelect(c)}><Avatar name={c.name} id={c.avatarId}/><div><strong>{c.name}</strong><span>{c.phone}</span></div><Plus size={18}/></button>)}{!filtered.length && <p>Không tìm thấy khách phù hợp.</p>}</div></>; }
