import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, CalendarDays, ChevronRight, LayoutGrid, List, Plus, Search, Phone, CarFront, X } from 'lucide-react';
import { useResource } from '../lib/hooks';
import { normalize, relativeContact, formatDate, clockTime, today, localDateTime } from '../lib/utils';
import { statuses, kinds, type Customer, type AgendaItem } from '../lib/types';
import { Avatar, Status, Empty, Loading, ErrorState } from '../components/ui';
import { CustomerForm } from '../components/forms';
import { SortMenu, type CustomerSort } from '../components/SortMenu';

export function Customers() {
  const customers = useResource<Customer[]>('/api/customers'); const agenda = useResource<AgendaItem[]>('/api/agenda');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [sort, setSort] = useState<CustomerSort>('name'); const [view, setView] = useState<'list' | 'grid'>('list'); const [adding, setAdding] = useState(false); const navigate = useNavigate();
  const list = useMemo(() => (customers.data || []).filter(c => (status === 'all' || c.status === status) && normalize(`${c.name} ${c.phone} ${c.vehicles.map(v => v.model + ' ' + v.plate).join(' ')}`).includes(normalize(search.trim()))).sort((a, b) => sort === 'recent' ? b.updatedAt.localeCompare(a.updatedAt) : sort === 'contact' ? (a.lastContactAt || '').localeCompare(b.lastContactAt || '') : a.name.localeCompare(b.name, 'vi')), [customers.data, search, status, sort]);
  const next = new Map<string, AgendaItem>(); for (const item of agenda.data || []) if (!next.has(item.customerId)) next.set(item.customerId, item);
  return <><section className="page-heading"><div><span className="eyebrow">KHÔNG GIAN CHĂM SÓC</span><h1>Khách hàng<span className="title-dot">.</span></h1><p>Mỗi mối quan hệ, một hành trình đáng trân trọng.</p></div><button className="button primary" onClick={() => setAdding(true)}><Plus size={18}/> Thêm khách hàng</button></section>
    <div className="customers-layout"><section className="customer-workspace"><div className="workspace-top"><div><h2>Các mối quan hệ của bạn <span className="count-badge">{customers.data?.length || 0}</span></h2><p>Luôn nhớ những điều quan trọng về khách hàng.</p></div></div>
      <div className="search-sort"><div className="search-field"><Search size={19}/><input aria-label="Tìm khách hàng" placeholder="Tìm tên, điện thoại, dòng xe hoặc biển số…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <button className="icon-button" aria-label="Xóa tìm kiếm" onClick={() => setSearch('')}><X size={16}/></button>}</div><SortMenu value={sort} onChange={setSort}/><div className="view-toggle"><button aria-label="Xem danh sách" aria-pressed={view === 'list'} className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={17}/></button><button aria-label="Xem dạng thẻ" aria-pressed={view === 'grid'} className={view === 'grid' ? 'active' : ''} onClick={() => setView('grid')}><LayoutGrid size={16}/></button></div></div>
      <div className="filter-row"><div className="filter-tabs" aria-label="Lọc trạng thái">{[['all', 'Tất cả'], ...Object.entries(statuses)].map(([key, label]) => <button className={status === key ? 'active' : ''} aria-pressed={status === key} key={key} onClick={() => setStatus(key)}>{label}<span>{key === 'all' ? customers.data?.length || 0 : customers.data?.filter(c => c.status === key).length || 0}</span></button>)}</div></div>
      {customers.loading ? <Loading/> : customers.error ? <ErrorState message={customers.error} retry={customers.reload}/> : !list.length ? <Empty title={search || status !== 'all' ? 'Chưa tìm thấy khách phù hợp' : 'Bắt đầu một mối quan hệ'} text={search || status !== 'all' ? 'Thử tìm từ khóa khác hoặc đổi bộ lọc.' : 'Thêm khách hàng đầu tiên và lưu những điều bạn muốn ghi nhớ.'} action={<button className="button secondary" onClick={() => { if (search || status !== 'all') { setSearch(''); setStatus('all'); } else setAdding(true); }}>{search || status !== 'all' ? 'Xóa bộ lọc' : 'Thêm khách hàng'}</button>}/> : <>
        {view === 'list' && <div className="list-columns" aria-hidden="true"><span>KHÁCH HÀNG</span><span>XE & TRẠNG THÁI</span><span>CHĂM SÓC GẦN NHẤT</span><span/></div>}
        <div className={`customer-list ${view}`}>{list.map(c => <Link className="customer-row" to={`/customers/${c.id}`} key={c.id}><div className="customer-identity"><Avatar name={c.name} id={c.avatarId}/><div><h3>{c.name}</h3><span className="muted"><Phone size={12}/>{c.phone}</span></div></div><div className="customer-car"><span className="car-model"><CarFront size={15}/>{c.vehicles[0]?.model || 'Chưa có thông tin xe'}{c.vehicles.length > 1 && <small>+{c.vehicles.length - 1}</small>}</span><Status value={c.status}/></div><div className="customer-care"><span>{relativeContact(c.lastContactAt)}</span>{next.get(c.id) ? <small className={new Date(next.get(c.id)!.occurrence.scheduledAt).getTime() < Date.now() ? 'overdue-text' : ''}><CalendarDays size={12}/> {formatDate(next.get(c.id)!.occurrence.scheduledAt)}</small> : <small>Chưa có lịch hẹn</small>}</div><ChevronRight size={17} className="row-chevron"/></Link>)}</div><div className="list-footer"><span>Hiển thị {list.length} / {customers.data?.length} khách hàng</span><span className="footer-tip">Một lần hỏi thăm, nhiều điều khác biệt.</span></div>
      </>}
    </section><aside className="companion"><DailyAgenda items={agenda.data || []} loading={agenda.loading} error={agenda.error} retry={agenda.reload}/><div className="relationship-note"><div className="note-mark">“</div><h3>Chăm sóc bắt đầu<br/>từ sự thấu hiểu.</h3><p>Một lời hỏi thăm đúng lúc giúp hành trình cùng khách hàng luôn tiếp nối.</p><div className="note-line"/><span>THE ART OF CLIENT CARE</span></div></aside></div>
    {adding && <CustomerForm onClose={() => setAdding(false)} onSaved={c => { setAdding(false); navigate(`/customers/${c.id}`); }}/>}</>;
}
function DailyAgenda({ items, loading, error, retry }: { items: AgendaItem[]; loading: boolean; error: string; retry: () => void }) {
  const [day, setDay] = useState(today()); const base = new Date(`${today()}T12:00:00+07:00`);
  const days = Array.from({ length: 7 }, (_, i) => { const date = new Date(base.getTime() + i * 86400000); return { date: localDateTime(date).slice(0, 10), number: new Intl.DateTimeFormat('vi-VN', { day: 'numeric', timeZone: 'Asia/Ho_Chi_Minh' }).format(date), label: i === 0 ? 'Nay' : new Intl.DateTimeFormat('vi-VN', { weekday: 'short', timeZone: 'Asia/Ho_Chi_Minh' }).format(date).replace('Thứ ', 'T') }; });
  const selected = items.filter(i => localDateTime(new Date(i.occurrence.scheduledAt)).slice(0, 10) === day);
  const overdue = items.filter(i => localDateTime(new Date(i.occurrence.scheduledAt)).slice(0, 10) < today());
  return <section className="agenda-preview"><header><div className="mini-icon"><CalendarDays size={18}/></div><h2>Lịch chăm sóc</h2><Link to="/agenda" aria-label="Xem toàn bộ lịch chăm sóc" className="icon-button"><ArrowRight size={17}/></Link></header><div className="week-strip">{days.map(d => <button key={d.date} className={day === d.date ? 'selected' : ''} onClick={() => setDay(d.date)} aria-pressed={day === d.date} aria-label={formatDate(d.date)}><span>{d.label}</span><strong>{d.number}</strong><i className={items.some(i => localDateTime(new Date(i.occurrence.scheduledAt)).slice(0, 10) === d.date) ? 'has-event' : ''}/></button>)}</div><div className="agenda-day-label">{day === today() ? 'HÔM NAY' : formatDate(day).toUpperCase()}<span>{selected.length} lịch hẹn</span></div>
    {loading ? <Loading/> : error ? <ErrorState message={error} retry={retry}/> : selected.length ? <div className="mini-agenda-list">{selected.slice(0, 4).map(item => <Link key={item.occurrence.id} to={`/customers/${item.customerId}?tab=reminders&occurrence=${item.occurrence.id}`} className="mini-agenda-item"><span className="agenda-time">{clockTime(item.occurrence.scheduledAt)}</span><div><strong>{item.customerName}</strong><p>{kinds[item.reminder.kind]}</p></div><ChevronRight size={14}/></Link>)}</div> : <div className="calm-empty"><CalendarDays size={25} strokeWidth={1.2}/><strong>Một khoảng trống để kết nối.</strong><p>Chưa có lịch hẹn trong ngày này.</p></div>}
    {overdue.length > 0 && <Link className="overdue-callout" to="/agenda?filter=overdue">{overdue.length} lịch đang chờ bạn chăm sóc <ArrowRight size={14}/></Link>}
    <Link className="agenda-all" to="/agenda">Xem tất cả lịch hẹn <ArrowRight size={15}/></Link></section>;
}
