import { useRef, useState, type ChangeEvent } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Bell, CalendarDays, Camera, CarFront, Check, Clock3, HeartHandshake, Images, Info, MessageCircle, Pencil, Phone, Plus, Trash2, Upload, LoaderCircle } from 'lucide-react';
import { useResource, useToast } from '../lib/hooks';
import { compressPhoto, post, put, remove, request } from '../lib/api';
import { age, formatDate, formatTime, relativeContact } from '../lib/utils';
import { channels, kinds, type Customer, type Contact, type Photo, type Reminder, type Occurrence, type ReminderRow } from '../lib/types';
import { Avatar, Empty, ErrorState, Loading, Modal, PhotoImage, Status, FormError } from '../components/ui';
import { ContactForm, CustomerForm, ReminderForm, SnoozeForm } from '../components/forms';
import { useConfirm, useDiscardChanges } from '../components/confirmation';

export function Profile() {
  const confirm = useConfirm();
  const { id } = useParams(); const resource = useResource<Customer>(`/api/customers/${id}`); const contacts = useResource<Contact[]>(`/api/customers/${id}/contacts`);
  const [params, setParams] = useSearchParams(); const tab = ['info', 'photos', 'care', 'reminders'].includes(params.get('tab') || '') ? params.get('tab')! : 'info';
  const [editing, setEditing] = useState(false); const [contacting, setContacting] = useState(false); const [reminding, setReminding] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const avatarInput = useRef<HTMLInputElement>(null); const toast = useToast();
  const customer = resource.data;
  async function uploadAvatar(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; e.target.value = ''; if (!file || !customer) return; setUploading(true); setError(''); try { const form = new FormData(); form.append('file', await compressPhoto(file), 'avatar.jpg'); form.append('avatar', 'true'); await request(`/api/customers/${customer.id}/photos`, { method: 'POST', body: form }); toast('Đã cập nhật ảnh đại diện.'); resource.reload(); } catch (e) { setError((e as Error).message); } finally { setUploading(false); } }
  async function deleteAvatar() { if (uploading || !customer?.avatarId || !await confirm({ title: 'Xóa ảnh đại diện?', description: `Ảnh đại diện của ${customer.name} sẽ bị xóa khỏi kho ảnh. Bạn cần tải lại ảnh nếu muốn sử dụng lại.`, confirmLabel: 'Xóa ảnh đại diện', cancelLabel: 'Giữ ảnh', tone: 'danger' })) return; setUploading(true); setError(''); try { await remove(`/api/photos/${customer.avatarId}`); toast('Đã xóa ảnh đại diện.'); resource.reload(); } catch (e) { setError((e as Error).message); } finally { setUploading(false); } }
  if (resource.loading) return <Loading/>;
  if (resource.error || !customer) return <ErrorState message={resource.error || 'Không tìm thấy khách hàng.'} retry={resource.reload}/>;
  return <><Link className="back-link" to="/"><ArrowLeft size={16}/> Khách hàng <span>/</span> Hồ sơ</Link><section className="profile-heading"><div className="profile-person"><button className="avatar-edit" onClick={() => avatarInput.current?.click()} aria-label="Đổi ảnh đại diện" disabled={uploading}><Avatar name={customer.name} id={customer.avatarId} large/><span>{uploading ? <LoaderCircle size={15} className="spin"/> : <Camera size={15}/>}</span></button><input ref={avatarInput} type="file" accept="image/*" className="sr-only" aria-label="Chọn ảnh đại diện" onChange={uploadAvatar}/><div><span className="eyebrow">HỒ SƠ KHÁCH HÀNG</span><h1>{customer.name}</h1><div className="profile-meta"><Status value={customer.status}/><span>{customer.phone}</span>{customer.avatarId && <button className="text-button muted" disabled={uploading} onClick={deleteAvatar}>Xóa ảnh đại diện</button>}</div></div></div><button className="button secondary" onClick={() => setEditing(true)}><Pencil size={16}/> Chỉnh sửa hồ sơ</button></section><FormError message={error}/>
    <div className="profile-mobile-actions"><a className="button primary" href={`tel:${customer.phone}`}><Phone size={15}/> Gọi khách</a><a className="button secondary" href={`sms:${customer.phone}`}><MessageCircle size={15}/> Nhắn tin</a></div>
    <div className="profile-layout"><aside className="profile-aside"><section className="panel quick-contact"><span className="eyebrow">GIỮ KẾT NỐI</span><h3>Một cuộc trò chuyện<br/>tạo nên khác biệt.</h3><a className="button primary" href={`tel:${customer.phone}`}><Phone size={16}/> Gọi khách hàng <ArrowUpRight size={15}/></a><a className="button secondary" href={`sms:${customer.phone}`}><MessageCircle size={16}/> Nhắn tin</a><div className="contact-preference"><Clock3 size={16}/><p>{customer.preferredContact || 'Chưa có thời gian liên hệ ưu tiên.'}</p></div><div className="last-contact"><span>Chăm sóc gần nhất</span><strong>{relativeContact(contacts.data?.[0]?.at)}</strong></div></section><section className="profile-note"><span className="eyebrow">MỖI KHÁCH HÀNG LÀ DUY NHẤT</span><p>Lưu một sở thích.<br/>Nhớ một ngày đặc biệt.<br/>Kết nối bằng sự quan tâm.</p></section></aside><section className="panel profile-content"><div className="profile-tabs" role="tablist" aria-label="Các mục trong hồ sơ">{[['info', 'Thông tin', Info], ['photos', 'Hình ảnh', Images], ['care', 'Chăm sóc', HeartHandshake], ['reminders', 'Lịch nhắc', Bell]].map(([key, label, Icon]) => { const TabIcon = Icon as typeof Info; return <button role="tab" id={`tab-${key}`} aria-controls="profile-tab-panel" aria-selected={tab === key} tabIndex={tab === key ? 0 : -1} key={String(key)} className={tab === key ? 'active' : ''} onKeyDown={e => { const tabs = ['info', 'photos', 'care', 'reminders']; if (['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? 3 : (tabs.indexOf(tab) + (e.key === 'ArrowRight' ? 1 : 3)) % 4; setParams({ tab: tabs[next] }); document.getElementById(`tab-${tabs[next]}`)?.focus(); } }} onClick={() => setParams(key === 'info' ? {} : { tab: String(key) })}><TabIcon size={17}/>{label as string}</button>; })}</div><div role="tabpanel" id="profile-tab-panel" aria-labelledby={`tab-${tab}`} className="tab-content">
      {tab === 'info' && <InfoTab customer={customer} onRemind={() => setReminding(true)}/>}
      {tab === 'photos' && <PhotosTab customerId={customer.id}/>}
      {tab === 'care' && <><div className="section-heading"><div><h2>Lịch sử chăm sóc</h2><p>Mỗi lần liên hệ đều được ghi nhớ.</p></div><button className="button primary small" onClick={() => setContacting(true)}><Plus size={16}/> Ghi nhận</button></div>{contacts.loading ? <Loading/> : contacts.error ? <ErrorState message={contacts.error} retry={contacts.reload}/> : !contacts.data?.length ? <Empty title="Chưa có lần chăm sóc nào" text="Ghi nhận cuộc trò chuyện đầu tiên với khách hàng."/> : <div className="care-timeline">{contacts.data.map(c => <article key={c.id}><div className="timeline-marker">{c.channel === 'call' ? <Phone size={16}/> : c.channel === 'message' ? <MessageCircle size={16}/> : <HeartHandshake size={16}/>}</div><div><div className="timeline-heading"><h3>{channels[c.channel]}</h3><time>{formatTime(c.at)}</time></div><p>{c.content}</p></div></article>)}</div>}</>}
      {tab === 'reminders' && <RemindersTab customer={customer} highlight={params.get('occurrence')} onCareChanged={contacts.reload}/>}
    </div></section></div>
    {editing && <CustomerForm customer={customer} onClose={() => setEditing(false)} onSaved={() => { setEditing(false); resource.reload(); }}/>} {contacting && <ContactForm customerId={customer.id} customerName={customer.name} onClose={() => setContacting(false)} onSaved={() => { setContacting(false); contacts.reload(); }}/>} {reminding && <ReminderForm customerId={customer.id} customerName={customer.name} onClose={() => setReminding(false)} onSaved={() => { setReminding(false); setParams({ tab: 'reminders' }); }}/>}</>;
}
function InfoTab({ customer: c, onRemind }: { customer: Customer; onRemind: () => void }) {
  return <><div className="section-heading"><div><h2>Những điều về {c.name.split(' · ')[0].split(' ').slice(-2).join(' ')}</h2><p>Chi tiết nhỏ giúp sự quan tâm trở nên khác biệt.</p></div></div><div className="info-grid"><div><span>HỌ VÀ TÊN</span><strong>{c.name}</strong></div><div><span>SỐ ĐIỆN THOẠI</span><a href={`tel:${c.phone}`}>{c.phone}</a></div><div><span>NGÀY SINH</span><strong>{formatDate(c.birthDate)}</strong>{c.birthDate && <small>{age(c.birthDate)} tuổi</small>}</div><div><span>TRẠNG THÁI</span><Status value={c.status}/></div></div><div className="detail-block"><h3>Sở thích & điều quan tâm</h3><p>{c.interests || 'Chưa bổ sung sở thích của khách hàng.'}</p></div><div className="detail-block"><h3>Ghi chú riêng</h3><p>{c.notes || 'Chưa có ghi chú. Bạn có thể bổ sung khi chỉnh sửa hồ sơ.'}</p></div><div className="section-heading vehicles-heading"><div><h2>Xe & hành trình đồng hành</h2><p>{c.vehicles.length ? `${c.vehicles.length} xe trong hồ sơ` : 'Thông tin xe có thể được bổ sung sau.'}</p></div><CarFront size={24} strokeWidth={1.2}/></div><div className="vehicle-cards">{c.vehicles.map((v, i) => <article className="vehicle-card" key={v.id || i}><div className="vehicle-art" aria-hidden="true"><CarFront size={47} strokeWidth={1}/><span>0{i + 1}</span></div><div><h3>{v.model || 'Chưa có dòng xe'}</h3><div className="vehicle-details"><span>Biển số<strong className="plate">{v.plate || 'Chưa bổ sung'}</strong></span><span>Ngày giao xe<strong>{formatDate(v.deliveryDate)}</strong></span></div></div></article>)}</div><div className="profile-remind"><CalendarDays size={25} strokeWidth={1.3}/><div><h3>Ghi nhớ một ngày đặc biệt.</h3><p>Sinh nhật, bảo dưỡng hay một lần hỏi thăm sau mua.</p></div><button className="button secondary small" onClick={onRemind}>Đặt lịch nhắc <Plus size={15}/></button></div></>;
}
function PhotosTab({ customerId }: { customerId: string }) {
  const photos = useResource<Photo[]>(`/api/customers/${customerId}/photos`); const input = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(''); const [error, setError] = useState(''); const [selected, setSelected] = useState<Photo>(); const toast = useToast();
  async function upload(e: ChangeEvent<HTMLInputElement>) { const files = Array.from(e.target.files || []); e.target.value = ''; if (!files.length) return; setBusy(true); setError(''); let uploaded = 0; try { for (const file of files) { setProgress(`Đang tải ảnh ${uploaded + 1}/${files.length}…`); const form = new FormData(); form.append('file', await compressPhoto(file), 'photo.jpg'); await request(`/api/customers/${customerId}/photos`, { method: 'POST', body: form }); uploaded++; } toast(`Đã thêm ${uploaded} ảnh vào album.`); } catch (e) { setError(`${uploaded ? `Đã thêm ${uploaded} ảnh. ` : ''}${(e as Error).message}`); } finally { setBusy(false); setProgress(''); photos.reload(); } }
  return <><div className="section-heading"><div><h2>Những khoảnh khắc đồng hành</h2><p>Ảnh giao xe, kỷ niệm và những điều đáng nhớ.</p></div><button className="button primary small" disabled={busy} onClick={() => input.current?.click()}>{busy ? <LoaderCircle size={16} className="spin"/> : <Plus size={16}/>} Thêm ảnh</button><input ref={input} className="sr-only" type="file" multiple accept="image/*" aria-label="Chọn ảnh album" onChange={upload}/></div><FormError message={error}/>{progress && <div className="field-note" role="status">{progress}</div>}{photos.loading ? <Loading/> : photos.error ? <ErrorState message={photos.error} retry={photos.reload}/> : !photos.data?.length ? <div className="photo-upload-empty"><Upload size={30} strokeWidth={1.3}/><h3>Lưu khoảnh khắc đầu tiên</h3><p>Chọn nhiều ảnh cùng lúc. Ảnh được tối ưu trước khi lưu.</p><button className="button secondary" disabled={busy} onClick={() => input.current?.click()}>Chọn ảnh từ thiết bị</button></div> : <div className="photo-grid">{photos.data.map(photo => <button className="photo-card" key={photo.id} onClick={() => setSelected(photo)}><PhotoImage id={photo.id} alt={photo.caption || 'Ảnh khách hàng'}/><div><strong>{photo.caption || 'Thêm một dòng ghi nhớ…'}</strong><span>{formatDate(photo.createdAt)}</span></div></button>)}</div>}{selected && <PhotoViewer photo={selected} onClose={() => setSelected(undefined)} onSaved={() => { setSelected(undefined); photos.reload(); }}/>}</>;
}
function PhotoViewer({ photo, onClose, onSaved }: { photo: Photo; onClose: () => void; onSaved: () => void }) {
  const confirm = useConfirm();
  const [caption, setCaption] = useState(photo.caption); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toast = useToast();
  const close = useDiscardChanges({ dirty: caption !== photo.caption, busy, onClose, description: 'Mô tả ảnh đang chỉnh sửa chưa được lưu. Bạn có thể tiếp tục chỉnh sửa để giữ nội dung này.' });
  async function save() { setBusy(true); setError(''); try { await put(`/api/photos/${photo.id}`, { caption }); toast('Đã lưu mô tả ảnh.'); onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function deletePhoto() { if (busy || !await confirm({ title: 'Xóa ảnh khỏi album?', description: 'Ảnh này sẽ bị xóa khỏi kho ảnh cùng với mô tả. Bạn cần tải lại ảnh nếu muốn sử dụng lại.', confirmLabel: 'Xóa ảnh', cancelLabel: 'Giữ ảnh', tone: 'danger' })) return; setBusy(true); setError(''); try { await remove(`/api/photos/${photo.id}`); toast('Đã xóa ảnh.'); onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Một khoảnh khắc đáng nhớ" onClose={close} wide busy={busy}><PhotoImage id={photo.id} alt={caption || 'Ảnh khách hàng'} className="photo-lightbox"/><label>Mô tả ảnh<textarea rows={2} maxLength={500} value={caption} disabled={busy} onChange={e => setCaption(e.target.value)}/></label><FormError message={error}/><div className="form-actions"><button className="text-button danger" disabled={busy} onClick={deletePhoto}><Trash2 size={16}/> Xóa ảnh</button><button className="button primary" disabled={busy} onClick={save}>{busy ? 'Đang lưu…' : 'Lưu mô tả'}</button></div></Modal>;
}
function RemindersTab({ customer, highlight, onCareChanged }: { customer: Customer; highlight: string | null; onCareChanged: () => void }) {
  const confirm = useConfirm();
  const resource = useResource<ReminderRow[]>(`/api/customers/${customer.id}/reminders`); const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<Reminder>(); const [action, setAction] = useState<{ type: 'snooze' | 'contact'; occurrence: Occurrence }>(); const [showPast, setShowPast] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const toast = useToast();
  async function perform(path: string, type: 'complete' | 'cancel') { if (busy || !await confirm(type === 'cancel' ? { title: 'Hủy lịch chăm sóc?', description: `Lịch của ${customer.name} và tất cả các lần chưa thực hiện sẽ được hủy. Những lần đã hoàn thành vẫn được giữ trong lịch sử.`, confirmLabel: 'Hủy lịch nhắc', cancelLabel: 'Giữ lịch', tone: 'danger' } : { title: 'Hoàn thành lần nhắc?', description: `Đánh dấu lần nhắc này của ${customer.name} là đã hoàn thành. Các lần lặp tiếp theo vẫn được giữ.`, confirmLabel: 'Hoàn thành', cancelLabel: 'Quay lại', tone: 'success' })) return; setBusy(true); setError(''); try { if (type === 'cancel') await remove(path); else await post(path); toast(type === 'cancel' ? 'Đã hủy lịch nhắc.' : 'Đã hoàn thành lần nhắc.'); resource.reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const saved = () => { setAdding(false); setEditing(undefined); setAction(undefined); resource.reload(); onCareChanged(); };
  const rows = resource.data?.filter(row => showPast || row.reminder.active && row.occurrences.some(o => o.state === 'pending') || row.occurrences.some(o => o.id === highlight)) || [];
  function occurrenceActions(o: Occurrence) { return o.state === 'pending' ? <div className="occurrence-actions"><button className="button secondary small" disabled={busy} onClick={() => setAction({ type: 'contact', occurrence: o })}>Ghi nhận chăm sóc</button><button className="icon-button" disabled={busy} aria-label="Dời lần nhắc" onClick={() => setAction({ type: 'snooze', occurrence: o })}><Clock3 size={17}/></button><button className="icon-button success" disabled={busy} aria-label="Hoàn thành lần nhắc" onClick={() => perform(`/api/occurrences/${o.id}/complete`, 'complete')}><Check size={17}/></button></div> : <span className={`status ${o.state === 'completed' ? 'purchased' : ''}`}>{o.state === 'completed' ? 'Đã hoàn thành' : 'Đã hủy'}</span>; }
  return <><div className="section-heading"><div><h2>Không bỏ lỡ sự quan tâm</h2><p>Lịch chăm sóc riêng cho khách hàng này.</p></div><button className="button primary small" onClick={() => setAdding(true)}><Plus size={16}/> Đặt lịch</button></div><label className="check history-toggle"><input type="checkbox" checked={showPast} onChange={e => setShowPast(e.target.checked)}/> Hiển thị cả lịch đã hoàn thành / đã hủy</label><FormError message={error}/>{resource.loading ? <Loading/> : resource.error ? <ErrorState message={resource.error} retry={resource.reload}/> : !rows.length ? <Empty title="Chưa có lịch đang chờ" text="Đặt lịch cho một dịp đặc biệt, hoặc một lần chăm sóc tiếp theo."/> : <div className="reminder-list">{rows.map(({ reminder: r, occurrences }) => { const first = occurrences.find(o => o.id === highlight) || occurrences.find(o => o.state === 'pending') || occurrences[0]; return <article className={`reminder-card ${occurrences.some(o => o.id === highlight) ? 'highlight' : ''}`} key={r.id}><div className="reminder-card-heading"><span className="reminder-kind"><Bell size={15}/>{kinds[r.kind]}{r.repeat === 'annual' && <small>Hằng năm</small>}{!r.active && <small>Đã hủy</small>}</span><div><button className="icon-button" aria-label="Sửa lịch nhắc" disabled={busy} onClick={() => setEditing(r)}><Pencil size={15}/></button>{r.active && <button className="icon-button danger" aria-label="Hủy lịch nhắc" disabled={busy} onClick={() => perform(`/api/reminders/${r.id}`, 'cancel')}><Trash2 size={15}/></button>}</div></div><h3>{r.content}</h3>{first && <><div className="reminder-when"><CalendarDays size={16}/><strong>{formatTime(first.scheduledAt)}</strong>{first.state === 'pending' && new Date(first.scheduledAt).getTime() < Date.now() && <span className="overdue-text">Quá hạn</span>}</div><p className="field-note">{r.leadDays ? `Nhắc trước ${r.leadDays} ngày` : 'Nhắc đúng giờ'} · Giờ Việt Nam</p>{occurrenceActions(first)}</>}{occurrences.length > 1 && <details><summary>Lịch sử & các lần tiếp theo ({occurrences.length - 1})</summary>{occurrences.filter(o => o.id !== first?.id).map(o => <div className="other-occurrence" key={o.id}><span>{formatTime(o.scheduledAt)}</span>{occurrenceActions(o)}</div>)}</details>}</article>; })}</div>}
    {(adding || editing) && <ReminderForm customerId={customer.id} customerName={customer.name} reminder={editing} onClose={() => { setAdding(false); setEditing(undefined); }} onSaved={saved}/>}{action?.type === 'snooze' && <SnoozeForm occurrence={action.occurrence} onClose={() => setAction(undefined)} onSaved={saved}/>} {action?.type === 'contact' && <ContactForm customerId={customer.id} customerName={customer.name} occurrence={action.occurrence} onClose={() => setAction(undefined)} onSaved={saved}/>}</>;
}
